//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActualBinding) DeepCopyInto(out *ActualBinding) {
	*out = *in
	if in.Vendor != nil {
		in, out := &in.Vendor, &out.Vendor
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.Serial != nil {
		in, out := &in.Serial, &out.Serial
		*out = new(string)
		**out = **in
	}
	if in.NodeUID != nil {
		in, out := &in.NodeUID, &out.NodeUID
		*out = new(string)
		**out = **in
	}
	if in.BootID != nil {
		in, out := &in.BootID, &out.BootID
		*out = new(string)
		**out = **in
	}
	if in.BDF != nil {
		in, out := &in.BDF, &out.BDF
		*out = new(string)
		**out = **in
	}
	if in.FunctionKey != nil {
		in, out := &in.FunctionKey, &out.FunctionKey
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(SourceRef)
		**out = **in
	}
	if in.EvidenceID != nil {
		in, out := &in.EvidenceID, &out.EvidenceID
		*out = new(string)
		**out = **in
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActualBinding.
func (in *ActualBinding) DeepCopy() *ActualBinding {
	if in == nil {
		return nil
	}
	out := new(ActualBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AffectedWorkload) DeepCopyInto(out *AffectedWorkload) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AffectedWorkload.
func (in *AffectedWorkload) DeepCopy() *AffectedWorkload {
	if in == nil {
		return nil
	}
	out := new(AffectedWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationSummary) DeepCopyInto(out *AllocationSummary) {
	*out = *in
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(string)
		**out = **in
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.EvidenceRefs != nil {
		in, out := &in.EvidenceRefs, &out.EvidenceRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AffectedWorkloads != nil {
		in, out := &in.AffectedWorkloads, &out.AffectedWorkloads
		*out = make([]AffectedWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationSummary.
func (in *AllocationSummary) DeepCopy() *AllocationSummary {
	if in == nil {
		return nil
	}
	out := new(AllocationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoverageSummary) DeepCopyInto(out *CoverageSummary) {
	*out = *in
	if in.EvidenceRefs != nil {
		in, out := &in.EvidenceRefs, &out.EvidenceRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.LatestObservedAt != nil {
		in, out := &in.LatestObservedAt, &out.LatestObservedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoverageSummary.
func (in *CoverageSummary) DeepCopy() *CoverageSummary {
	if in == nil {
		return nil
	}
	out := new(CoverageSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSummary) DeepCopyInto(out *DeviceSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSummary.
func (in *DeviceSummary) DeepCopy() *DeviceSummary {
	if in == nil {
		return nil
	}
	out := new(DeviceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceSummary) DeepCopyInto(out *EvidenceSummary) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceSummary.
func (in *EvidenceSummary) DeepCopy() *EvidenceSummary {
	if in == nil {
		return nil
	}
	out := new(EvidenceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingSummary) DeepCopyInto(out *FindingSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingSummary.
func (in *FindingSummary) DeepCopy() *FindingSummary {
	if in == nil {
		return nil
	}
	out := new(FindingSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetCoverageRequirement) DeepCopyInto(out *FleetCoverageRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetCoverageRequirement.
func (in *FleetCoverageRequirement) DeepCopy() *FleetCoverageRequirement {
	if in == nil {
		return nil
	}
	out := new(FleetCoverageRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDevice) DeepCopyInto(out *GPUDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDevice.
func (in *GPUDevice) DeepCopy() *GPUDevice {
	if in == nil {
		return nil
	}
	out := new(GPUDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceList) DeepCopyInto(out *GPUDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceList.
func (in *GPUDeviceList) DeepCopy() *GPUDeviceList {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceSpec) DeepCopyInto(out *GPUDeviceSpec) {
	*out = *in
	out.NodeRef = in.NodeRef
	in.InventoryClaim.DeepCopyInto(&out.InventoryClaim)
	out.FleetRef = in.FleetRef
	out.Request = in.Request
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceSpec.
func (in *GPUDeviceSpec) DeepCopy() *GPUDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceStatus) DeepCopyInto(out *GPUDeviceStatus) {
	*out = *in
	in.IntentObservedAt.DeepCopyInto(&out.IntentObservedAt)
	in.ActualBinding.DeepCopyInto(&out.ActualBinding)
	if in.GraphRevision != nil {
		in, out := &in.GraphRevision, &out.GraphRevision
		*out = new(string)
		**out = **in
	}
	in.Allocation.DeepCopyInto(&out.Allocation)
	if in.Coverage != nil {
		in, out := &in.Coverage, &out.Coverage
		*out = make([]CoverageSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FindingRefs != nil {
		in, out := &in.FindingRefs, &out.FindingRefs
		*out = make([]FindingSummary, len(*in))
		copy(*out, *in)
	}
	if in.EvidenceRefs != nil {
		in, out := &in.EvidenceRefs, &out.EvidenceRefs
		*out = make([]EvidenceSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceStatus.
func (in *GPUDeviceStatus) DeepCopy() *GPUDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFleet) DeepCopyInto(out *GPUFleet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFleet.
func (in *GPUFleet) DeepCopy() *GPUFleet {
	if in == nil {
		return nil
	}
	out := new(GPUFleet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUFleet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFleetList) DeepCopyInto(out *GPUFleetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUFleet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFleetList.
func (in *GPUFleetList) DeepCopy() *GPUFleetList {
	if in == nil {
		return nil
	}
	out := new(GPUFleetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUFleetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFleetSpec) DeepCopyInto(out *GPUFleetSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.RequiredCoverage != nil {
		in, out := &in.RequiredCoverage, &out.RequiredCoverage
		*out = make([]FleetCoverageRequirement, len(*in))
		copy(*out, *in)
	}
	if in.CanarySelector != nil {
		in, out := &in.CanarySelector, &out.CanarySelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFleetSpec.
func (in *GPUFleetSpec) DeepCopy() *GPUFleetSpec {
	if in == nil {
		return nil
	}
	out := new(GPUFleetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUFleetStatus) DeepCopyInto(out *GPUFleetStatus) {
	*out = *in
	if in.AssessmentRevision != nil {
		in, out := &in.AssessmentRevision, &out.AssessmentRevision
		*out = new(string)
		**out = **in
	}
	if in.OwnedNodeRefs != nil {
		in, out := &in.OwnedNodeRefs, &out.OwnedNodeRefs
		*out = make([]OwnedNodeRef, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUFleetStatus.
func (in *GPUFleetStatus) DeepCopy() *GPUFleetStatus {
	if in == nil {
		return nil
	}
	out := new(GPUFleetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GateOwnershipPolicy) DeepCopyInto(out *GateOwnershipPolicy) {
	*out = *in
	if in.RequiredCoverage != nil {
		in, out := &in.RequiredCoverage, &out.RequiredCoverage
		*out = make([]FleetCoverageRequirement, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GateOwnershipPolicy.
func (in *GateOwnershipPolicy) DeepCopy() *GateOwnershipPolicy {
	if in == nil {
		return nil
	}
	out := new(GateOwnershipPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GateOwnershipStatus) DeepCopyInto(out *GateOwnershipStatus) {
	*out = *in
	in.Policy.DeepCopyInto(&out.Policy)
	in.CleanupRequestedAt.DeepCopyInto(&out.CleanupRequestedAt)
	if in.RecoveryStartedAt != nil {
		in, out := &in.RecoveryStartedAt, &out.RecoveryStartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastRecoveryPointAt != nil {
		in, out := &in.LastRecoveryPointAt, &out.LastRecoveryPointAt
		*out = (*in).DeepCopy()
	}
	if in.RecoveryControllerID != nil {
		in, out := &in.RecoveryControllerID, &out.RecoveryControllerID
		*out = new(string)
		**out = **in
	}
	if in.LastRecoveryDigest != nil {
		in, out := &in.LastRecoveryDigest, &out.LastRecoveryDigest
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GateOwnershipStatus.
func (in *GateOwnershipStatus) DeepCopy() *GateOwnershipStatus {
	if in == nil {
		return nil
	}
	out := new(GateOwnershipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventoryClaim) DeepCopyInto(out *InventoryClaim) {
	*out = *in
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.Serial != nil {
		in, out := &in.Serial, &out.Serial
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventoryClaim.
func (in *InventoryClaim) DeepCopy() *InventoryClaim {
	if in == nil {
		return nil
	}
	out := new(InventoryClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleRequest) DeepCopyInto(out *LifecycleRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleRequest.
func (in *LifecycleRequest) DeepCopy() *LifecycleRequest {
	if in == nil {
		return nil
	}
	out := new(LifecycleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePathState) DeepCopyInto(out *NodePathState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePathState.
func (in *NodePathState) DeepCopy() *NodePathState {
	if in == nil {
		return nil
	}
	out := new(NodePathState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePathState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePathStateList) DeepCopyInto(out *NodePathStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodePathState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePathStateList.
func (in *NodePathStateList) DeepCopy() *NodePathStateList {
	if in == nil {
		return nil
	}
	out := new(NodePathStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePathStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePathStateSpec) DeepCopyInto(out *NodePathStateSpec) {
	*out = *in
	out.NodeRef = in.NodeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePathStateSpec.
func (in *NodePathStateSpec) DeepCopy() *NodePathStateSpec {
	if in == nil {
		return nil
	}
	out := new(NodePathStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePathStateStatus) DeepCopyInto(out *NodePathStateStatus) {
	*out = *in
	out.NodeRef = in.NodeRef
	if in.GraphRevision != nil {
		in, out := &in.GraphRevision, &out.GraphRevision
		*out = new(string)
		**out = **in
	}
	if in.CollectorSession != nil {
		in, out := &in.CollectorSession, &out.CollectorSession
		*out = new(int64)
		**out = **in
	}
	if in.DeviceSummaries != nil {
		in, out := &in.DeviceSummaries, &out.DeviceSummaries
		*out = make([]DeviceSummary, len(*in))
		copy(*out, *in)
	}
	if in.GateOwnership != nil {
		in, out := &in.GateOwnership, &out.GateOwnership
		*out = new(GateOwnershipStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePathStateStatus.
func (in *NodePathStateStatus) DeepCopy() *NodePathStateStatus {
	if in == nil {
		return nil
	}
	out := new(NodePathStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedNodeRef) DeepCopyInto(out *OwnedNodeRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedNodeRef.
func (in *OwnedNodeRef) DeepCopy() *OwnedNodeRef {
	if in == nil {
		return nil
	}
	out := new(OwnedNodeRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRef) DeepCopyInto(out *SourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRef.
func (in *SourceRef) DeepCopy() *SourceRef {
	if in == nil {
		return nil
	}
	out := new(SourceRef)
	in.DeepCopyInto(out)
	return out
}
