//go:build cgo && ((darwin && arm64) || (linux && (amd64 || arm64)))

package nativepcie

/*
#cgo CFLAGS: -I${SRCDIR}/csrc
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/../../build/native/darwin-arm64/libdpa_pcie.a
#cgo linux,amd64 LDFLAGS: ${SRCDIR}/../../build/native/linux-amd64/libdpa_pcie.a
#cgo linux,arm64 LDFLAGS: ${SRCDIR}/../../build/native/linux-arm64/libdpa_pcie.a

// dpa_pcie_stamp.h is generated by `make native` from a digest of the native
// source, header, compiler identity, flags and target. It lives in this
// package directory so the Go build cache keys on it and cannot silently
// reuse an obsolete external archive. Run `make native` if it is missing.
#include "dpa_pcie_stamp.h"
#include "dpa_pcie.h"
*/
import "C"

import (
	"fmt"
	"os"
	"syscall"
	"unsafe"
)

// buildStamp records which native inputs this bridge was compiled against.
// It is a package-level variable, not a constant, and is read at runtime so
// the digest string is materialized in this package's compiled output: the
// Go build cache keys downstream link and test actions on package content,
// so a changed stamp forces binaries to be relinked against the new archive
// instead of silently reusing one built from an obsolete archive.
var buildStamp = string(C.DPA_PCIE_BUILD_STAMP) + "/" + string(C.DPA_PCIE_BUILD_TARGET)

// Platform open flags used by ReadDevice on the supported (POSIX) targets.
// They live here, not in device.go, so unavailable-stub targets that lack
// these syscall constants still build.
const (
	openDirFlags   = syscall.O_DIRECTORY
	openFieldFlags = syscall.O_NONBLOCK
)

// Compile-time guard that the header limits match the Go constants.
var _ [MaxTextLen - C.DPA_PCIE_MAX_TEXT]struct{}
var _ [C.DPA_PCIE_MAX_TEXT - MaxTextLen]struct{}

func backendAvailable() bool {
	return buildStamp != "" &&
		uint32(C.dpa_pcie_abi_version()) == uint32(C.DPA_PCIE_ABI_VERSION) &&
		uint32(C.DPA_PCIE_ABI_VERSION) == 1
}

// statusError maps a native status to a wrapped sentinel; nil on success.
// Any status outside the six defined ABI values maps to ErrUnavailable.
func statusError(op string, st C.dpa_pcie_status) error {
	switch st {
	case C.DPA_PCIE_OK:
		return nil
	case C.DPA_PCIE_INVALID:
		return fmt.Errorf("nativepcie: %s: %w", op, ErrInvalid)
	case C.DPA_PCIE_RANGE:
		return fmt.Errorf("nativepcie: %s: %w", op, ErrRange)
	case C.DPA_PCIE_NODATA:
		return fmt.Errorf("nativepcie: %s: %w", op, ErrNoData)
	case C.DPA_PCIE_TOO_LARGE:
		return fmt.Errorf("nativepcie: %s: %w", op, ErrTooLarge)
	case C.DPA_PCIE_IO:
		return fmt.Errorf("nativepcie: %s: %w", op, ErrIO)
	default:
		return fmt.Errorf("nativepcie: %s: undefined native status %d: %w", op, int64(st), ErrUnavailable)
	}
}

// cBytes returns a C pointer/length pair viewing data for the duration of a
// synchronous native call. A nil or empty slice yields a NULL pointer and
// length zero, which every text parser treats as empty text.
func cBytes(data []byte) (*C.char, C.size_t) {
	if len(data) == 0 {
		return nil, 0
	}
	return (*C.char)(unsafe.Pointer(unsafe.SliceData(data))), C.size_t(len(data))
}

func backendParseBDF(s string) (BDF, error) {
	var out C.dpa_pcie_bdf
	var ptr *C.char
	if len(s) > 0 {
		ptr = (*C.char)(unsafe.Pointer(unsafe.StringData(s)))
	}
	st := C.dpa_pcie_parse_bdf(ptr, C.size_t(len(s)), &out)
	if err := statusError("parse bdf", st); err != nil {
		return BDF{}, err
	}
	return BDF{
		Domain:   uint16(out.domain),
		Bus:      uint8(out.bus),
		Device:   uint8(out.device),
		Function: uint8(out.function),
	}, nil
}

func backendParseWidth(data []byte) (uint32, error) {
	var out C.uint32_t
	ptr, n := cBytes(data)
	st := C.dpa_pcie_parse_width(ptr, n, &out)
	if err := statusError("parse width", st); err != nil {
		return 0, err
	}
	return uint32(out), nil
}

func backendParseSpeed(data []byte) (uint32, error) {
	var out C.uint32_t
	ptr, n := cBytes(data)
	st := C.dpa_pcie_parse_speed(ptr, n, &out)
	if err := statusError("parse speed", st); err != nil {
		return 0, err
	}
	return uint32(out), nil
}

func backendParseNUMA(data []byte) (int32, error) {
	var out C.int32_t
	ptr, n := cBytes(data)
	st := C.dpa_pcie_parse_numa(ptr, n, &out)
	if err := statusError("parse numa", st); err != nil {
		return 0, err
	}
	return int32(out), nil
}

func backendParseAER(data []byte) ([]AERCounter, error) {
	var out C.dpa_pcie_aer
	ptr, n := cBytes(data)
	st := C.dpa_pcie_parse_aer(ptr, n, &out)
	if err := statusError("parse aer", st); err != nil {
		return nil, err
	}
	count := int(out.count)
	if count > len(out.entries) {
		return nil, fmt.Errorf("nativepcie: parse aer: entry count %d exceeds %d: %w",
			count, len(out.entries), ErrUnavailable)
	}
	counters := make([]AERCounter, 0, count)
	for i := 0; i < count; i++ {
		entry := &out.entries[i]
		name := unsafe.Slice((*byte)(unsafe.Pointer(&entry.name[0])), len(entry.name))
		end := 0
		for end < len(name) && name[end] != 0 {
			end++
		}
		// string(...) copies the label into Go-owned memory.
		counters = append(counters, AERCounter{Name: string(name[:end]), Count: uint64(entry.count)})
	}
	return counters, nil
}

func backendReadFile(f *os.File) ([]byte, error) {
	const op = "read file"
	if f == nil {
		return nil, fmt.Errorf("nativepcie: %s: nil file: %w", op, ErrInvalid)
	}
	// Stat first: a closed *os.File fails here with an error matching
	// fs.ErrClosed (wrapped together with ErrIO below), and nonregular
	// objects are rejected without ever blocking on them.
	info, err := f.Stat()
	if err != nil {
		return nil, fmt.Errorf("nativepcie: %s: %w: %w", op, ErrIO, err)
	}
	if !info.Mode().IsRegular() {
		return nil, fmt.Errorf("nativepcie: %s %q: %w: not a regular file (%s)",
			op, f.Name(), ErrIO, info.Mode().Type())
	}
	conn, err := f.SyscallConn()
	if err != nil {
		return nil, fmt.Errorf("nativepcie: %s: %w: %w", op, ErrIO, err)
	}

	// The buffer is Go memory without pointers; C only writes into it during
	// the synchronous call below and retains nothing.
	buf := make([]byte, MaxTextLen+1)
	var (
		st      C.dpa_pcie_status
		outLen  C.size_t
		outErrn C.int
	)
	// Control keeps the descriptor alive (and unclosed) for the call.
	err = conn.Control(func(fd uintptr) {
		st = C.dpa_pcie_read_fd(C.int(fd), (*C.char)(unsafe.Pointer(&buf[0])),
			C.size_t(len(buf)), &outLen, &outErrn)
	})
	if err != nil {
		return nil, fmt.Errorf("nativepcie: %s: %w: %w", op, ErrIO, err)
	}
	if st == C.DPA_PCIE_IO && outErrn != 0 {
		return nil, fmt.Errorf("nativepcie: %s %q: %w: %w", op, f.Name(), ErrIO, syscall.Errno(outErrn))
	}
	if err := statusError(op, st); err != nil {
		return nil, err
	}
	n := int(outLen)
	if n < 0 || n > MaxTextLen {
		return nil, fmt.Errorf("nativepcie: %s: native length %d out of bounds: %w", op, n, ErrUnavailable)
	}
	// Return a fresh Go-owned copy without the terminating NUL.
	return append([]byte{}, buf[:n]...), nil
}
