// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: dpa/ingest/v1alpha1/ingest.proto

package ingestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Completeness int32

const (
	Completeness_COMPLETENESS_UNSPECIFIED Completeness = 0
	Completeness_COMPLETE                 Completeness = 1
	Completeness_PARTIAL                  Completeness = 2
)

// Enum value maps for Completeness.
var (
	Completeness_name = map[int32]string{
		0: "COMPLETENESS_UNSPECIFIED",
		1: "COMPLETE",
		2: "PARTIAL",
	}
	Completeness_value = map[string]int32{
		"COMPLETENESS_UNSPECIFIED": 0,
		"COMPLETE":                 1,
		"PARTIAL":                  2,
	}
)

func (x Completeness) Enum() *Completeness {
	p := new(Completeness)
	*p = x
	return p
}

func (x Completeness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Completeness) Descriptor() protoreflect.EnumDescriptor {
	return file_dpa_ingest_v1alpha1_ingest_proto_enumTypes[0].Descriptor()
}

func (Completeness) Type() protoreflect.EnumType {
	return &file_dpa_ingest_v1alpha1_ingest_proto_enumTypes[0]
}

func (x Completeness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Completeness.Descriptor instead.
func (Completeness) EnumDescriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{0}
}

type AckCode int32

const (
	AckCode_ACK_CODE_UNSPECIFIED AckCode = 0
	AckCode_ACCEPTED             AckCode = 1
	AckCode_DUPLICATE            AckCode = 2
	AckCode_OUT_OF_ORDER         AckCode = 3 // GFL-083 (value numbers are GLI)
	AckCode_GAP                  AckCode = 4
	AckCode_WRONG_SESSION        AckCode = 5
	AckCode_CONFLICT             AckCode = 6
	AckCode_INVALID              AckCode = 7
)

// Enum value maps for AckCode.
var (
	AckCode_name = map[int32]string{
		0: "ACK_CODE_UNSPECIFIED",
		1: "ACCEPTED",
		2: "DUPLICATE",
		3: "OUT_OF_ORDER",
		4: "GAP",
		5: "WRONG_SESSION",
		6: "CONFLICT",
		7: "INVALID",
	}
	AckCode_value = map[string]int32{
		"ACK_CODE_UNSPECIFIED": 0,
		"ACCEPTED":             1,
		"DUPLICATE":            2,
		"OUT_OF_ORDER":         3,
		"GAP":                  4,
		"WRONG_SESSION":        5,
		"CONFLICT":             6,
		"INVALID":              7,
	}
)

func (x AckCode) Enum() *AckCode {
	p := new(AckCode)
	*p = x
	return p
}

func (x AckCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckCode) Descriptor() protoreflect.EnumDescriptor {
	return file_dpa_ingest_v1alpha1_ingest_proto_enumTypes[1].Descriptor()
}

func (AckCode) Type() protoreflect.EnumType {
	return &file_dpa_ingest_v1alpha1_ingest_proto_enumTypes[1]
}

func (x AckCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckCode.Descriptor instead.
func (AckCode) EnumDescriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{1}
}

type AllocationProfile int32

const (
	AllocationProfile_ALLOCATION_PROFILE_UNSPECIFIED AllocationProfile = 0
	AllocationProfile_NVIDIA_PODRESOURCES_UUID       AllocationProfile = 1
	AllocationProfile_UNSUPPORTED                    AllocationProfile = 2
)

// Enum value maps for AllocationProfile.
var (
	AllocationProfile_name = map[int32]string{
		0: "ALLOCATION_PROFILE_UNSPECIFIED",
		1: "NVIDIA_PODRESOURCES_UUID",
		2: "UNSUPPORTED",
	}
	AllocationProfile_value = map[string]int32{
		"ALLOCATION_PROFILE_UNSPECIFIED": 0,
		"NVIDIA_PODRESOURCES_UUID":       1,
		"UNSUPPORTED":                    2,
	}
)

func (x AllocationProfile) Enum() *AllocationProfile {
	p := new(AllocationProfile)
	*p = x
	return p
}

func (x AllocationProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AllocationProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_dpa_ingest_v1alpha1_ingest_proto_enumTypes[2].Descriptor()
}

func (AllocationProfile) Type() protoreflect.EnumType {
	return &file_dpa_ingest_v1alpha1_ingest_proto_enumTypes[2]
}

func (x AllocationProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AllocationProfile.Descriptor instead.
func (AllocationProfile) EnumDescriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{2}
}

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ClientFrame_Hello
	//	*ClientFrame_Snapshot
	Frame         isClientFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetFrame() isClientFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ClientFrame) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientFrame) GetSnapshot() *SnapshotFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isClientFrame_Frame interface {
	isClientFrame_Frame()
}

type ClientFrame_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientFrame_Snapshot struct {
	Snapshot *SnapshotFrame `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

func (*ClientFrame_Hello) isClientFrame_Frame() {}

func (*ClientFrame_Snapshot) isClientFrame_Frame() {}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ServerFrame_Hello
	//	*ServerFrame_Ack
	Frame         isServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetFrame() isServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ServerFrame) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ServerFrame) GetAck() *SnapshotAck {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isServerFrame_Frame interface {
	isServerFrame_Frame()
}

type ServerFrame_Hello struct {
	Hello *ServerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ServerFrame_Ack struct {
	Ack *SnapshotAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*ServerFrame_Hello) isServerFrame_Frame() {}

func (*ServerFrame_Ack) isServerFrame_Frame() {}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"` // GFL-082
	NodeUid       string                 `protobuf:"bytes,4,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"`
	BootId        string                 `protobuf:"bytes,5,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientHello) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClientHello) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ClientHello) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *ClientHello) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type ServerHello struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Session            int64                  `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	CollectorProfileId string                 `protobuf:"bytes,2,opt,name=collector_profile_id,json=collectorProfileId,proto3" json:"collector_profile_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *ServerHello) GetSession() int64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *ServerHello) GetCollectorProfileId() string {
	if x != nil {
		return x.CollectorProfileId
	}
	return ""
}

type SnapshotFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeUid        string                 `protobuf:"bytes,1,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"`
	BootId         string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Session        int64                  `protobuf:"varint,3,opt,name=session,proto3" json:"session,omitempty"`
	Sequence       uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Completeness   Completeness           `protobuf:"varint,5,opt,name=completeness,proto3,enum=dpa.ingest.v1alpha1.Completeness" json:"completeness,omitempty"`
	ObservedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Payload        *HostSnapshotV1        `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadDigest  []byte                 `protobuf:"bytes,8,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"`
	BundleRevision string                 `protobuf:"bytes,9,opt,name=bundle_revision,json=bundleRevision,proto3" json:"bundle_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SnapshotFrame) Reset() {
	*x = SnapshotFrame{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFrame) ProtoMessage() {}

func (x *SnapshotFrame) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFrame.ProtoReflect.Descriptor instead.
func (*SnapshotFrame) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotFrame) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *SnapshotFrame) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *SnapshotFrame) GetSession() int64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *SnapshotFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SnapshotFrame) GetCompleteness() Completeness {
	if x != nil {
		return x.Completeness
	}
	return Completeness_COMPLETENESS_UNSPECIFIED
}

func (x *SnapshotFrame) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *SnapshotFrame) GetPayload() *HostSnapshotV1 {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SnapshotFrame) GetPayloadDigest() []byte {
	if x != nil {
		return x.PayloadDigest
	}
	return nil
}

func (x *SnapshotFrame) GetBundleRevision() string {
	if x != nil {
		return x.BundleRevision
	}
	return ""
}

type SnapshotAck struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Code                 AckCode                `protobuf:"varint,1,opt,name=code,proto3,enum=dpa.ingest.v1alpha1.AckCode" json:"code,omitempty"`
	AcceptedSession      int64                  `protobuf:"varint,2,opt,name=accepted_session,json=acceptedSession,proto3" json:"accepted_session,omitempty"` // GFL-083
	ExpectedNextSequence uint64                 `protobuf:"varint,3,opt,name=expected_next_sequence,json=expectedNextSequence,proto3" json:"expected_next_sequence,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SnapshotAck) Reset() {
	*x = SnapshotAck{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotAck) ProtoMessage() {}

func (x *SnapshotAck) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotAck.ProtoReflect.Descriptor instead.
func (*SnapshotAck) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotAck) GetCode() AckCode {
	if x != nil {
		return x.Code
	}
	return AckCode_ACK_CODE_UNSPECIFIED
}

func (x *SnapshotAck) GetAcceptedSession() int64 {
	if x != nil {
		return x.AcceptedSession
	}
	return 0
}

func (x *SnapshotAck) GetExpectedNextSequence() uint64 {
	if x != nil {
		return x.ExpectedNextSequence
	}
	return 0
}

func (x *SnapshotAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HostSnapshotV1 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Assets          []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Edges           []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	EdgeEvidence    []*EdgeEvidence        `protobuf:"bytes,3,rep,name=edge_evidence,json=edgeEvidence,proto3" json:"edge_evidence,omitempty"`
	Observations    []*Observation         `protobuf:"bytes,4,rep,name=observations,proto3" json:"observations,omitempty"`
	GpuBindings     []*GPUBinding          `protobuf:"bytes,5,rep,name=gpu_bindings,json=gpuBindings,proto3" json:"gpu_bindings,omitempty"`
	AllocationBatch *AllocationBatch       `protobuf:"bytes,6,opt,name=allocation_batch,json=allocationBatch,proto3" json:"allocation_batch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HostSnapshotV1) Reset() {
	*x = HostSnapshotV1{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSnapshotV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSnapshotV1) ProtoMessage() {}

func (x *HostSnapshotV1) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSnapshotV1.ProtoReflect.Descriptor instead.
func (*HostSnapshotV1) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *HostSnapshotV1) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *HostSnapshotV1) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *HostSnapshotV1) GetEdgeEvidence() []*EdgeEvidence {
	if x != nil {
		return x.EdgeEvidence
	}
	return nil
}

func (x *HostSnapshotV1) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *HostSnapshotV1) GetGpuBindings() []*GPUBinding {
	if x != nil {
		return x.GpuBindings
	}
	return nil
}

func (x *HostSnapshotV1) GetAllocationBatch() *AllocationBatch {
	if x != nil {
		return x.AllocationBatch
	}
	return nil
}

type Alias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alias) Reset() {
	*x = Alias{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *Alias) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Alias) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Canonical     string                 `protobuf:"bytes,2,opt,name=canonical,proto3" json:"canonical,omitempty"`
	Aliases       []*Alias               `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{8}
}

func (x *Asset) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Asset) GetCanonical() string {
	if x != nil {
		return x.Canonical
	}
	return ""
}

func (x *Asset) GetAliases() []*Alias {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromKey       string                 `protobuf:"bytes,1,opt,name=from_key,json=fromKey,proto3" json:"from_key,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	ToKey         string                 `protobuf:"bytes,3,opt,name=to_key,json=toKey,proto3" json:"to_key,omitempty"`
	Origin        string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{9}
}

func (x *Edge) GetFromKey() string {
	if x != nil {
		return x.FromKey
	}
	return ""
}

func (x *Edge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Edge) GetToKey() string {
	if x != nil {
		return x.ToKey
	}
	return ""
}

func (x *Edge) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type EdgeEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeIndex     uint32                 `protobuf:"varint,1,opt,name=edge_index,json=edgeIndex,proto3" json:"edge_index,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // GFL-083
	SourceName    string                 `protobuf:"bytes,4,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	EvidenceId    string                 `protobuf:"bytes,7,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeEvidence) Reset() {
	*x = EdgeEvidence{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeEvidence) ProtoMessage() {}

func (x *EdgeEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeEvidence.ProtoReflect.Descriptor instead.
func (*EdgeEvidence) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{10}
}

func (x *EdgeEvidence) GetEdgeIndex() uint32 {
	if x != nil {
		return x.EdgeIndex
	}
	return 0
}

func (x *EdgeEvidence) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EdgeEvidence) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *EdgeEvidence) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *EdgeEvidence) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *EdgeEvidence) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EdgeEvidence) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

type SourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRef) Reset() {
	*x = SourceRef{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRef) ProtoMessage() {}

func (x *SourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRef.ProtoReflect.Descriptor instead.
func (*SourceRef) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{11}
}

func (x *SourceRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SourceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to V:
	//
	//	*Value_IntValue
	//	*Value_FloatValue
	//	*Value_BoolValue
	//	*Value_StringValue
	V             isValue_V `protobuf_oneof:"v"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{12}
}

func (x *Value) GetV() isValue_V {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.V.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.V.(*Value_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.V.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.V.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isValue_V interface {
	isValue_V()
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,2,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*Value_IntValue) isValue_V() {}

func (*Value_FloatValue) isValue_V() {}

func (*Value_BoolValue) isValue_V() {}

func (*Value_StringValue) isValue_V() {}

type Dimension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimension) Reset() {
	*x = Dimension{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimension) ProtoMessage() {}

func (x *Dimension) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimension.ProtoReflect.Descriptor instead.
func (*Dimension) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{13}
}

func (x *Dimension) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Dimension) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Observation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        *SourceRef             `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Subject       *Asset                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Signal        string                 `protobuf:"bytes,4,opt,name=signal,proto3" json:"signal,omitempty"`
	Value         *Value                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Dimensions    []*Dimension           `protobuf:"bytes,7,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Sequence      uint64                 `protobuf:"varint,11,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Quality       string                 `protobuf:"bytes,12,opt,name=quality,proto3" json:"quality,omitempty"`
	RawDigest     string                 `protobuf:"bytes,13,opt,name=raw_digest,json=rawDigest,proto3" json:"raw_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{14}
}

func (x *Observation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Observation) GetSource() *SourceRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Observation) GetSubject() *Asset {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Observation) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *Observation) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Observation) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Observation) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Observation) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *Observation) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *Observation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Observation) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Observation) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *Observation) GetRawDigest() string {
	if x != nil {
		return x.RawDigest
	}
	return ""
}

type GPUBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Bdf           string                 `protobuf:"bytes,3,opt,name=bdf,proto3" json:"bdf,omitempty"`
	SourceType    string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // GFL-083
	SourceName    string                 `protobuf:"bytes,5,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	EvidenceId    string                 `protobuf:"bytes,6,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUBinding) Reset() {
	*x = GPUBinding{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUBinding) ProtoMessage() {}

func (x *GPUBinding) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUBinding.ProtoReflect.Descriptor instead.
func (*GPUBinding) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{15}
}

func (x *GPUBinding) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPUBinding) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *GPUBinding) GetBdf() string {
	if x != nil {
		return x.Bdf
	}
	return ""
}

func (x *GPUBinding) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *GPUBinding) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *GPUBinding) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *GPUBinding) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *GPUBinding) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type AllocationEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  string                 `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"` // GFL-083
	PodName       string                 `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerName string                 `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocationEntry) Reset() {
	*x = AllocationEntry{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationEntry) ProtoMessage() {}

func (x *AllocationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationEntry.ProtoReflect.Descriptor instead.
func (*AllocationEntry) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{16}
}

func (x *AllocationEntry) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *AllocationEntry) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AllocationEntry) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *AllocationEntry) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AllocationEntry) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type AllocationBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeUid       string                 `protobuf:"bytes,1,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"`
	BootId        string                 `protobuf:"bytes,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Session       int64                  `protobuf:"varint,3,opt,name=session,proto3" json:"session,omitempty"` // GFL-083
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Complete      bool                   `protobuf:"varint,7,opt,name=complete,proto3" json:"complete,omitempty"`
	EvidenceRefs  []string               `protobuf:"bytes,8,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	Profile       AllocationProfile      `protobuf:"varint,9,opt,name=profile,proto3,enum=dpa.ingest.v1alpha1.AllocationProfile" json:"profile,omitempty"`
	Entries       []*AllocationEntry     `protobuf:"bytes,10,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocationBatch) Reset() {
	*x = AllocationBatch{}
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationBatch) ProtoMessage() {}

func (x *AllocationBatch) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationBatch.ProtoReflect.Descriptor instead.
func (*AllocationBatch) Descriptor() ([]byte, []int) {
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP(), []int{17}
}

func (x *AllocationBatch) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *AllocationBatch) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AllocationBatch) GetSession() int64 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *AllocationBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AllocationBatch) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *AllocationBatch) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AllocationBatch) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *AllocationBatch) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *AllocationBatch) GetProfile() AllocationProfile {
	if x != nil {
		return x.Profile
	}
	return AllocationProfile_ALLOCATION_PROFILE_UNSPECIFIED
}

func (x *AllocationBatch) GetEntries() []*AllocationEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_dpa_ingest_v1alpha1_ingest_proto protoreflect.FileDescriptor

const file_dpa_ingest_v1alpha1_ingest_proto_rawDesc = "" +
	"\n" +
	" dpa/ingest/v1alpha1/ingest.proto\x12\x13dpa.ingest.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n" +
	"\vClientFrame\x128\n" +
	"\x05hello\x18\x01 \x01(\v2 .dpa.ingest.v1alpha1.ClientHelloH\x00R\x05hello\x12@\n" +
	"\bsnapshot\x18\x02 \x01(\v2\".dpa.ingest.v1alpha1.SnapshotFrameH\x00R\bsnapshotB\a\n" +
	"\x05frame\"\x86\x01\n" +
	"\vServerFrame\x128\n" +
	"\x05hello\x18\x01 \x01(\v2 .dpa.ingest.v1alpha1.ServerHelloH\x00R\x05hello\x124\n" +
	"\x03ack\x18\x02 \x01(\v2 .dpa.ingest.v1alpha1.SnapshotAckH\x00R\x03ackB\a\n" +
	"\x05frame\"\x97\x01\n" +
	"\vClientHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12\x19\n" +
	"\bnode_uid\x18\x04 \x01(\tR\anodeUid\x12\x17\n" +
	"\aboot_id\x18\x05 \x01(\tR\x06bootId\"Y\n" +
	"\vServerHello\x12\x18\n" +
	"\asession\x18\x01 \x01(\x03R\asession\x120\n" +
	"\x14collector_profile_id\x18\x02 \x01(\tR\x12collectorProfileId\"\x8c\x03\n" +
	"\rSnapshotFrame\x12\x19\n" +
	"\bnode_uid\x18\x01 \x01(\tR\anodeUid\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x18\n" +
	"\asession\x18\x03 \x01(\x03R\asession\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12E\n" +
	"\fcompleteness\x18\x05 \x01(\x0e2!.dpa.ingest.v1alpha1.CompletenessR\fcompleteness\x12;\n" +
	"\vobserved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12=\n" +
	"\apayload\x18\a \x01(\v2#.dpa.ingest.v1alpha1.HostSnapshotV1R\apayload\x12%\n" +
	"\x0epayload_digest\x18\b \x01(\fR\rpayloadDigest\x12'\n" +
	"\x0fbundle_revision\x18\t \x01(\tR\x0ebundleRevision\"\xba\x01\n" +
	"\vSnapshotAck\x120\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1c.dpa.ingest.v1alpha1.AckCodeR\x04code\x12)\n" +
	"\x10accepted_session\x18\x02 \x01(\x03R\x0facceptedSession\x124\n" +
	"\x16expected_next_sequence\x18\x03 \x01(\x04R\x14expectedNextSequence\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x98\x03\n" +
	"\x0eHostSnapshotV1\x122\n" +
	"\x06assets\x18\x01 \x03(\v2\x1a.dpa.ingest.v1alpha1.AssetR\x06assets\x12/\n" +
	"\x05edges\x18\x02 \x03(\v2\x19.dpa.ingest.v1alpha1.EdgeR\x05edges\x12F\n" +
	"\redge_evidence\x18\x03 \x03(\v2!.dpa.ingest.v1alpha1.EdgeEvidenceR\fedgeEvidence\x12D\n" +
	"\fobservations\x18\x04 \x03(\v2 .dpa.ingest.v1alpha1.ObservationR\fobservations\x12B\n" +
	"\fgpu_bindings\x18\x05 \x03(\v2\x1f.dpa.ingest.v1alpha1.GPUBindingR\vgpuBindings\x12O\n" +
	"\x10allocation_batch\x18\x06 \x01(\v2$.dpa.ingest.v1alpha1.AllocationBatchR\x0fallocationBatch\";\n" +
	"\x05Alias\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"o\n" +
	"\x05Asset\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tcanonical\x18\x02 \x01(\tR\tcanonical\x124\n" +
	"\aaliases\x18\x03 \x03(\v2\x1a.dpa.ingest.v1alpha1.AliasR\aaliases\"l\n" +
	"\x04Edge\x12\x19\n" +
	"\bfrom_key\x18\x01 \x01(\tR\afromKey\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x15\n" +
	"\x06to_key\x18\x03 \x01(\tR\x05toKey\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\"\x9c\x02\n" +
	"\fEdgeEvidence\x12\x1d\n" +
	"\n" +
	"edge_index\x18\x01 \x01(\rR\tedgeIndex\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x1f\n" +
	"\vsource_name\x18\x04 \x01(\tR\n" +
	"sourceName\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vevidence_id\x18\a \x01(\tR\n" +
	"evidenceId\"3\n" +
	"\tSourceRef\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x94\x01\n" +
	"\x05Value\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x02 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValueB\x03\n" +
	"\x01v\"3\n" +
	"\tDimension\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb3\x04\n" +
	"\vObservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x06source\x18\x02 \x01(\v2\x1e.dpa.ingest.v1alpha1.SourceRefR\x06source\x124\n" +
	"\asubject\x18\x03 \x01(\v2\x1a.dpa.ingest.v1alpha1.AssetR\asubject\x12\x16\n" +
	"\x06signal\x18\x04 \x01(\tR\x06signal\x120\n" +
	"\x05value\x18\x05 \x01(\v2\x1a.dpa.ingest.v1alpha1.ValueR\x05value\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12>\n" +
	"\n" +
	"dimensions\x18\a \x03(\v2\x1e.dpa.ingest.v1alpha1.DimensionR\n" +
	"dimensions\x12;\n" +
	"\vobserved_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12;\n" +
	"\vreceived_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1a\n" +
	"\bsequence\x18\v \x01(\x04R\bsequence\x12\x18\n" +
	"\aquality\x18\f \x01(\tR\aquality\x12\x1d\n" +
	"\n" +
	"raw_digest\x18\r \x01(\tR\trawDigest\"\xa5\x02\n" +
	"\n" +
	"GPUBinding\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x10\n" +
	"\x03bdf\x18\x03 \x01(\tR\x03bdf\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12\x1f\n" +
	"\vsource_name\x18\x05 \x01(\tR\n" +
	"sourceName\x12\x1f\n" +
	"\vevidence_id\x18\x06 \x01(\tR\n" +
	"evidenceId\x12;\n" +
	"\vobserved_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xba\x01\n" +
	"\x0fAllocationEntry\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12#\n" +
	"\rpod_namespace\x18\x03 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\"\xb6\x03\n" +
	"\x0fAllocationBatch\x12\x19\n" +
	"\bnode_uid\x18\x01 \x01(\tR\anodeUid\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\tR\x06bootId\x12\x18\n" +
	"\asession\x18\x03 \x01(\x03R\asession\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1a\n" +
	"\bcomplete\x18\a \x01(\bR\bcomplete\x12#\n" +
	"\revidence_refs\x18\b \x03(\tR\fevidenceRefs\x12@\n" +
	"\aprofile\x18\t \x01(\x0e2&.dpa.ingest.v1alpha1.AllocationProfileR\aprofile\x12>\n" +
	"\aentries\x18\n" +
	" \x03(\v2$.dpa.ingest.v1alpha1.AllocationEntryR\aentries*G\n" +
	"\fCompleteness\x12\x1c\n" +
	"\x18COMPLETENESS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCOMPLETE\x10\x01\x12\v\n" +
	"\aPARTIAL\x10\x02*\x89\x01\n" +
	"\aAckCode\x12\x18\n" +
	"\x14ACK_CODE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x01\x12\r\n" +
	"\tDUPLICATE\x10\x02\x12\x10\n" +
	"\fOUT_OF_ORDER\x10\x03\x12\a\n" +
	"\x03GAP\x10\x04\x12\x11\n" +
	"\rWRONG_SESSION\x10\x05\x12\f\n" +
	"\bCONFLICT\x10\x06\x12\v\n" +
	"\aINVALID\x10\a*f\n" +
	"\x11AllocationProfile\x12\"\n" +
	"\x1eALLOCATION_PROFILE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18NVIDIA_PODRESOURCES_UUID\x10\x01\x12\x0f\n" +
	"\vUNSUPPORTED\x10\x022Z\n" +
	"\x06Ingest\x12P\n" +
	"\x06Stream\x12 .dpa.ingest.v1alpha1.ClientFrame\x1a .dpa.ingest.v1alpha1.ServerFrame(\x010\x01BEZCgithub.com/aetertinas9/data-path-assurance/internal/ingest/ingestpbb\x06proto3"

var (
	file_dpa_ingest_v1alpha1_ingest_proto_rawDescOnce sync.Once
	file_dpa_ingest_v1alpha1_ingest_proto_rawDescData []byte
)

func file_dpa_ingest_v1alpha1_ingest_proto_rawDescGZIP() []byte {
	file_dpa_ingest_v1alpha1_ingest_proto_rawDescOnce.Do(func() {
		file_dpa_ingest_v1alpha1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dpa_ingest_v1alpha1_ingest_proto_rawDesc), len(file_dpa_ingest_v1alpha1_ingest_proto_rawDesc)))
	})
	return file_dpa_ingest_v1alpha1_ingest_proto_rawDescData
}

var file_dpa_ingest_v1alpha1_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dpa_ingest_v1alpha1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_dpa_ingest_v1alpha1_ingest_proto_goTypes = []any{
	(Completeness)(0),             // 0: dpa.ingest.v1alpha1.Completeness
	(AckCode)(0),                  // 1: dpa.ingest.v1alpha1.AckCode
	(AllocationProfile)(0),        // 2: dpa.ingest.v1alpha1.AllocationProfile
	(*ClientFrame)(nil),           // 3: dpa.ingest.v1alpha1.ClientFrame
	(*ServerFrame)(nil),           // 4: dpa.ingest.v1alpha1.ServerFrame
	(*ClientHello)(nil),           // 5: dpa.ingest.v1alpha1.ClientHello
	(*ServerHello)(nil),           // 6: dpa.ingest.v1alpha1.ServerHello
	(*SnapshotFrame)(nil),         // 7: dpa.ingest.v1alpha1.SnapshotFrame
	(*SnapshotAck)(nil),           // 8: dpa.ingest.v1alpha1.SnapshotAck
	(*HostSnapshotV1)(nil),        // 9: dpa.ingest.v1alpha1.HostSnapshotV1
	(*Alias)(nil),                 // 10: dpa.ingest.v1alpha1.Alias
	(*Asset)(nil),                 // 11: dpa.ingest.v1alpha1.Asset
	(*Edge)(nil),                  // 12: dpa.ingest.v1alpha1.Edge
	(*EdgeEvidence)(nil),          // 13: dpa.ingest.v1alpha1.EdgeEvidence
	(*SourceRef)(nil),             // 14: dpa.ingest.v1alpha1.SourceRef
	(*Value)(nil),                 // 15: dpa.ingest.v1alpha1.Value
	(*Dimension)(nil),             // 16: dpa.ingest.v1alpha1.Dimension
	(*Observation)(nil),           // 17: dpa.ingest.v1alpha1.Observation
	(*GPUBinding)(nil),            // 18: dpa.ingest.v1alpha1.GPUBinding
	(*AllocationEntry)(nil),       // 19: dpa.ingest.v1alpha1.AllocationEntry
	(*AllocationBatch)(nil),       // 20: dpa.ingest.v1alpha1.AllocationBatch
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_dpa_ingest_v1alpha1_ingest_proto_depIdxs = []int32{
	5,  // 0: dpa.ingest.v1alpha1.ClientFrame.hello:type_name -> dpa.ingest.v1alpha1.ClientHello
	7,  // 1: dpa.ingest.v1alpha1.ClientFrame.snapshot:type_name -> dpa.ingest.v1alpha1.SnapshotFrame
	6,  // 2: dpa.ingest.v1alpha1.ServerFrame.hello:type_name -> dpa.ingest.v1alpha1.ServerHello
	8,  // 3: dpa.ingest.v1alpha1.ServerFrame.ack:type_name -> dpa.ingest.v1alpha1.SnapshotAck
	0,  // 4: dpa.ingest.v1alpha1.SnapshotFrame.completeness:type_name -> dpa.ingest.v1alpha1.Completeness
	21, // 5: dpa.ingest.v1alpha1.SnapshotFrame.observed_at:type_name -> google.protobuf.Timestamp
	9,  // 6: dpa.ingest.v1alpha1.SnapshotFrame.payload:type_name -> dpa.ingest.v1alpha1.HostSnapshotV1
	1,  // 7: dpa.ingest.v1alpha1.SnapshotAck.code:type_name -> dpa.ingest.v1alpha1.AckCode
	11, // 8: dpa.ingest.v1alpha1.HostSnapshotV1.assets:type_name -> dpa.ingest.v1alpha1.Asset
	12, // 9: dpa.ingest.v1alpha1.HostSnapshotV1.edges:type_name -> dpa.ingest.v1alpha1.Edge
	13, // 10: dpa.ingest.v1alpha1.HostSnapshotV1.edge_evidence:type_name -> dpa.ingest.v1alpha1.EdgeEvidence
	17, // 11: dpa.ingest.v1alpha1.HostSnapshotV1.observations:type_name -> dpa.ingest.v1alpha1.Observation
	18, // 12: dpa.ingest.v1alpha1.HostSnapshotV1.gpu_bindings:type_name -> dpa.ingest.v1alpha1.GPUBinding
	20, // 13: dpa.ingest.v1alpha1.HostSnapshotV1.allocation_batch:type_name -> dpa.ingest.v1alpha1.AllocationBatch
	10, // 14: dpa.ingest.v1alpha1.Asset.aliases:type_name -> dpa.ingest.v1alpha1.Alias
	21, // 15: dpa.ingest.v1alpha1.EdgeEvidence.observed_at:type_name -> google.protobuf.Timestamp
	21, // 16: dpa.ingest.v1alpha1.EdgeEvidence.expires_at:type_name -> google.protobuf.Timestamp
	14, // 17: dpa.ingest.v1alpha1.Observation.source:type_name -> dpa.ingest.v1alpha1.SourceRef
	11, // 18: dpa.ingest.v1alpha1.Observation.subject:type_name -> dpa.ingest.v1alpha1.Asset
	15, // 19: dpa.ingest.v1alpha1.Observation.value:type_name -> dpa.ingest.v1alpha1.Value
	16, // 20: dpa.ingest.v1alpha1.Observation.dimensions:type_name -> dpa.ingest.v1alpha1.Dimension
	21, // 21: dpa.ingest.v1alpha1.Observation.observed_at:type_name -> google.protobuf.Timestamp
	21, // 22: dpa.ingest.v1alpha1.Observation.received_at:type_name -> google.protobuf.Timestamp
	21, // 23: dpa.ingest.v1alpha1.Observation.expires_at:type_name -> google.protobuf.Timestamp
	21, // 24: dpa.ingest.v1alpha1.GPUBinding.observed_at:type_name -> google.protobuf.Timestamp
	21, // 25: dpa.ingest.v1alpha1.GPUBinding.expires_at:type_name -> google.protobuf.Timestamp
	21, // 26: dpa.ingest.v1alpha1.AllocationBatch.observed_at:type_name -> google.protobuf.Timestamp
	21, // 27: dpa.ingest.v1alpha1.AllocationBatch.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 28: dpa.ingest.v1alpha1.AllocationBatch.profile:type_name -> dpa.ingest.v1alpha1.AllocationProfile
	19, // 29: dpa.ingest.v1alpha1.AllocationBatch.entries:type_name -> dpa.ingest.v1alpha1.AllocationEntry
	3,  // 30: dpa.ingest.v1alpha1.Ingest.Stream:input_type -> dpa.ingest.v1alpha1.ClientFrame
	4,  // 31: dpa.ingest.v1alpha1.Ingest.Stream:output_type -> dpa.ingest.v1alpha1.ServerFrame
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_dpa_ingest_v1alpha1_ingest_proto_init() }
func file_dpa_ingest_v1alpha1_ingest_proto_init() {
	if File_dpa_ingest_v1alpha1_ingest_proto != nil {
		return
	}
	file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Hello)(nil),
		(*ClientFrame_Snapshot)(nil),
	}
	file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_Hello)(nil),
		(*ServerFrame_Ack)(nil),
	}
	file_dpa_ingest_v1alpha1_ingest_proto_msgTypes[12].OneofWrappers = []any{
		(*Value_IntValue)(nil),
		(*Value_FloatValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dpa_ingest_v1alpha1_ingest_proto_rawDesc), len(file_dpa_ingest_v1alpha1_ingest_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dpa_ingest_v1alpha1_ingest_proto_goTypes,
		DependencyIndexes: file_dpa_ingest_v1alpha1_ingest_proto_depIdxs,
		EnumInfos:         file_dpa_ingest_v1alpha1_ingest_proto_enumTypes,
		MessageInfos:      file_dpa_ingest_v1alpha1_ingest_proto_msgTypes,
	}.Build()
	File_dpa_ingest_v1alpha1_ingest_proto = out.File
	file_dpa_ingest_v1alpha1_ingest_proto_goTypes = nil
	file_dpa_ingest_v1alpha1_ingest_proto_depIdxs = nil
}
